/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddOrRemovePrograms: typeof import('./src/components/programs/AddOrRemovePrograms.vue')['default']
    AdminComponentMachine: typeof import('./src/components/admin/AdminComponentMachine.vue')['default']
    BackgroundImages: typeof import('./src/components/programs/pc-settings/BackgroundImages.vue')['default']
    ButtonComponent: typeof import('./src/components/utils/ButtonComponent.vue')['default']
    Calculator: typeof import('./src/components/programs/Calculator.vue')['default']
    Chattie: typeof import('./src/components/programs/Chattie.vue')['default']
    ChatWindow: typeof import('./src/components/programs/chattie/ChatWindow.vue')['default']
    Clock: typeof import('./src/components/taskbar/Clock.vue')['default']
    ColorTool: typeof import('./src/components/programs/paint/ColorTool.vue')['default']
    ComponentMachine: typeof import('./src/components/ComponentMachine.vue')['default']
    DesktopItem: typeof import('./src/components/DesktopItem.vue')['default']
    ErrorComponent: typeof import('./src/components/ErrorComponent.vue')['default']
    ErrorList: typeof import('./src/components/admin/ErrorList.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    Googol: typeof import('./src/components/programs/paw-explore/pages/googol.vue')['default']
    IconComponent: typeof import('./src/components/utils/IconComponent.vue')['default']
    ImageComponent: typeof import('./src/components/utils/ImageComponent.vue')['default']
    InputComponent: typeof import('./src/components/utils/InputComponent.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoginScreen: typeof import('./src/components/auth/LoginScreen.vue')['default']
    ManagePrograms: typeof import('./src/components/admin/managePrograms/ManagePrograms.vue')['default']
    ManageUsers: typeof import('./src/components/admin/manageUsers/ManageUsers.vue')['default']
    Menu: typeof import('./src/components/menuComponents/Menu.vue')['default']
    MenuItem: typeof import('./src/components/menuComponents/MenuItem.vue')['default']
    MinesweeperBlock: typeof import('./src/components/programs/minesweeper/MinesweeperBlock.vue')['default']
    MinesweeperGame: typeof import('./src/components/programs/MinesweeperGame.vue')['default']
    MyComputer: typeof import('./src/components/programs/MyComputer.vue')['default']
    Nasa: typeof import('./src/components/programs/paw-explore/pages/nasa.vue')['default']
    NetworkNeighborhood: typeof import('./src/components/programs/NetworkNeighborhood.vue')['default']
    Paint: typeof import('./src/components/programs/Paint.vue')['default']
    PAWDOS: typeof import('./src/components/programs/PAWDOS.vue')['default']
    PawExplore: typeof import('./src/components/programs/PawExplore.vue')['default']
    PawPlayer: typeof import('./src/components/programs/PawPlayer.vue')['default']
    PawPoint: typeof import('./src/components/programs/PawPoint.vue')['default']
    PCScreen: typeof import('./src/components/programs/pc-settings/PCScreen.vue')['default']
    PCSettings: typeof import('./src/components/programs/PCSettings.vue')['default']
    ProgramsList: typeof import('./src/components/programs/add-remove-programs/ProgramsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideTitleImage: typeof import('./src/components/programs/pawpoint/slides/SlideTitleImage.vue')['default']
    SlideTitleText: typeof import('./src/components/programs/pawpoint/slides/SlideTitleText.vue')['default']
    Taskbar: typeof import('./src/components/taskbar/Taskbar.vue')['default']
    UserInfo: typeof import('./src/components/auth/UserInfo.vue')['default']
    UsersList: typeof import('./src/components/admin/manageUsers/UsersList.vue')['default']
    Validating: typeof import('./src/components/Validating.vue')['default']
    WindowFrame: typeof import('./src/components/windowframe/WindowFrame.vue')['default']
    WindowframeMenu: typeof import('./src/components/windowframe/windowframeMenu.vue')['default']
  }
}
